### PR TITLE
Decouple virsorter2 database files from image/container

### PR DESCRIPTION
**Pull request by papanikos**
Hi @replikation @mult1fractal @hoelzer ,

This mainly addresses #121 .

I followed the same conventions as with the other tools that require an input db and created a separate module for fetching virsorter2 data. 
* A `virsorter2-db` directory is created in the provided `--databases` location.
* When unpacking the `tar.gz` permissions are set, so this solves my original issue.

A new dockerfile is also included under `phage-tool-Dockerfiles` , so feel free to do whatever you want with it.
* For testing I used my own image available [here](https://hub.docker.com/r/papanikos/virsorter-2/tags?page=1&ordering=last_updated) . I included this in the `container.config` and is included in this PR.

I only tested it with the local singularity profile like this
```
nextflow ./phage.nf \
-profile smalltest,local,singularity \
--workdir ./workdir \
--identify \
--dv --ma --sk --mp --pp --vs --sm --vb --vn --ph
```

and worked fine.

PS: Sorry for some commits changing the same file again and again, I had my issues...

### CODE REVIEW

**Comment by replikation** [comment]
* hi thanks for the PR, we are doing some testings and report back

**Comment by mult1fractal** [comment]
hey @papanikos 
I tested your additions on our `smalltest` profile without any error msg (will also do a bigger test)
good job 👍🏽 

I only have a minor request regarding the dockerfile:
* `withLabel: virsorter2 { container = 'papanikos/virsorter-2:latest' }` in the `container.config` file
* could you add a `tag` instead of `latest` like we did for the other dockerfiles? (its more stable this way)

otherwise if its okay for you I would take the dockerfile recipe, upload the docker to my docker-repo and add the tag myself

let me know if you change it or if I should do it and I will merge this branch into the main branch ;)

**Comment by papanikos** [comment]
Hi,
I am asking this to be consistent with the rest and because I am fairly new to this.

What would be your suggestion for proper tagging of images? There are a few suggestions around the interwebs
* semantic versioning -  `virsorter2:0.1` (image version? software version wrapped in the image?)
* commit based - `virsorter2:fa935f8` (based on some git commit hash)
* `sha256` based - `virsorter2:74cb6611be686460297618f492bda3c00fbdf155184acc447a3620d60c1ef530` 

I see you have used a combination of both semantic versioning and some hash.

Also, as a side note, [BioContainers](https://biocontainers.pro/registry) seems like a nice community for publishing bioinfrormatics software. It happens to have a `virsorter:2.2.1` [image](https://quay.io/repository/biocontainers/virsorter?tab=tags) but I cannot find out if it fits the purpose here.

**Comment by replikation** [comment]
Hi,

Yes tool:toolversion--commithash is usually a save bet. Biocontainer oftentimes lack the ps Program that nextflow needs and are also sometimes not compatible for cloud computing, that is why we often exchange them.

**Comment by papanikos** [comment]
Here we go!

**Review by replikation — APPROVED** [review]
@mult1fractal looks good on my end. we can merge do some testings for e.g. "setup" and do a release

**Comment by mult1fractal** [comment]
I will merge this branch into the master Branch 
but there is a minor issue with the heatmap pdf for virsorter 2... I think the filter is not working properly .. 
After I fixed it I will create an new release 👍🏽

**Pull request merged**
