### PR TITLE
rm container option that crashes singularity

### PR DESCRIPTION
**Pull request by hoelzer**
Removed the container option from

```bash
    withLabel: seqkit           { container = 'nanozoo/seqkit:0.13.2--cd66104' ; containerOptions = '--shm-size 2g' }
```

bc this is a Docker option and if coded like that it crashes Singularity. Also, it is probably not needed anyway. 

I am doing some further tests on SLURM/Singularity and will then report here if the PR is ready

### CODE REVIEW

**Comment by hoelzer** [comment]
VS2 fails:

Could not create conda environment from /opt/conda/lib/python3.8/site-packages/virsorter/rules/../envs/vs2.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 119, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python3.8/site-packages/mamba/mamba_env.py", line 44, in mamba_install
        index = load_channels(
      File "/opt/conda/lib/python3.8/site-packages/mamba/utils.py", line 93, in load_channels
        index = get_index(
      File "/opt/conda/lib/python3.8/site-packages/mamba/utils.py", line 74, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Download error (7) Couldn't connect to server [https://conda.anaconda.org/bioconda/noarch/repodata.json]
    Failed to connect to conda.anaconda.org port 443: Connection refused

`$ /opt/conda/bin/mamba create --quiet --file /scratch/hoelzerm/databases/wtp/nextflow-autodownload-databases/virsorter2-db/db/conda_envs/bd7b4199.yaml --prefix /scratch/hoelzerm/databases/wtp/nextflow-autodownload-databases/virsorter2-db/db/conda_envs/bd7b4199`


But maybe this is because of the RKI HPC setup... and nothing directly related to how SIngularity is configurred...

I am ignoring VS2 for now

**Comment by hoelzer** [comment]
The filter steps for virsorter and virsorter_virome failed for me when the output of viruses of cat 1,2,3,4 is empty. I integrated a check now if the file is empty. Will push the code soonish here as well

**Comment by mult1fractal** [comment]
can you do a testrun ? with the added code? I will merge it then

**Comment by hoelzer** [comment]
@mult1fractal I am on it.

THe filtering of virsorter (virome) works now for me. But now the test run fails at

[ce/4d99bf] process > phage_tax_classification_wf:sourmash_for_tax (8)       [100%] 8 of 8, failed: 8


Looking into it

**Comment by hoelzer** [comment]
Hm sorry, I dont have time to look into this further. I did some fixes as described above. Please have a look and if it is fine please merge @mult1fractal !

**Comment by mult1fractal** [comment]
I used the small-test and everything worked.
will merge now

**Pull request merged**
