### PR TITLE
SLURM + singularity support for HPC

### PR DESCRIPTION
**Pull request by mshamash**
Looks like the Nextflow configs for Slurm + singularity are all there, just a matter of merging the two branches.

This would be in addition to LSF support which WtP has now.

### CODE REVIEW

**Comment by replikation** [comment]
* singularity is implemented as i could test and validate this, I currently don't have access to a SLURM to test the code
* also I changed the config structure behind WtP quite heavily so this branch is outdated
* I can create a new branch with the added SLURM configuration, so someone can test this and report back if it's working?

**Comment by mshamash** [comment]
I’ll be able to test with SLURM in the coming days !

**Comment by hoelzer** [comment]
> I’ll be able to test with SLURM in the coming days !

That would be awesome, thx! I think I added the SLURM branch back then but was also not able to test it properly bc/ our HPC here does not have any singularity support at the moment. 

> I can create a new branch with the added SLURM configuration, so someone can test this and report back if it's working?

good idea

**Comment by replikation** [comment]
* okay perfect ill create a new branch and PR and tag you both the moment it can be tested
* closing this PR now as I won't merge this branch (@hoelzer don't delete this branch need the code :P )

**Pull request closed without merging**
