### PR TITLE
Marvel updated container 

### PR DESCRIPTION
**Pull request by papanikos**
This is for  #133 

* A new marvel docker container that contains a fix for marvel not crashing when empty fasta files are produced by prokka.

### CODE REVIEW

**Comment by replikation** [comment]
* prokka is a dependency?

**Review by replikation — APPROVED** [review]
@mult1fractal looks good

**Comment by papanikos** [comment]
`prokka` is a dependency of marvel (along with `hmmer` and few python packages like `biopython`, `scikit-learn`, `pandas` ). All of these are available on `conda` channels and are installed through `conda` in the container. This takes care of executables being available on path, by default. 

I had to pin some python packages to specific (older) versions, otherwise the models bundled with marvel could not be read.

**Comment by replikation** [comment]
@papanikos prokka has some nasty ncbi deps that get outdated if older than x months and "break" even a container. super annoying

**Pull request merged**
